hyperparameter_space:
  randomforestclassifier__bootstrap:
  - true
  - false
  randomforestclassifier__max_depth:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  - 100
  - 110
  - null
  randomforestclassifier__max_features:
  - null
  - sqrt
  randomforestclassifier__min_samples_leaf:
  - 1
  - 2
  - 3
  - 5
  - 10
  - 20
  randomforestclassifier__min_samples_split:
  - 2
  - 5
  - 10
  - 20
  randomforestclassifier__n_estimators:
  - 200
  - 400
  - 600
  - 800
  - 1000
  - 1200
  - 1400
  - 1600
  - 1800
  - 2000
model_name: RandomForestClassifier
scale: false
search_method: RandomizedSearchCV
